#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          on             \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    1.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  06             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^CrossOver$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^eqMac$" manage=off
yabai -m rule --add app="^Loop$" manage=off
yabai -m rule --add app="^Windows 11$" manage=off
yabai -m rule --add app="^Parallels Desktop$" manage=off
yabai -m rule --add app="^Swinsian$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^ProtonVPN$" manage=off
yabai -m rule --add app="^Raycast$" manage=off

# All games are set to unmanaged
yabai -m rule --add app="^EA$" manage=off
yabai -m rule --add app="^STAR WARS™ Battlefront™ II$" manage=off
yabai -m rule --add app="^Teardown$" manage=off
yabai -m rule --add app="^tModLoader$" manage=off
yabai -m rule --add app="^Terraria$" manage=off
yabai -m rule --add app="^Noita$" manage=off
yabai -m rule --add app="^WorldOfTanks.exe$" manage=off
yabai -m rule --add app="^wgc.exe$" manage=off
yabai -m rule --add app="^KingdomTwoCrowns$" manage=off
yabai -m rule --add app="^DiRT Rally$" manage=off

# Specific call to the finder
yabai -m rule --add app="^Finder$" manage=on
echo "yabai configuration loaded.."
