<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Exporters\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bunq.Core\Bunq.Core.csproj" />
    </ItemGroup>

</Project>
